name: Software Assurance CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-and-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Environment
        working-directory: Module_5
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Enforce Linting with Pylint
        # strictly enforce a score of 10 for source code integrity here
        working-directory: Module_5
        run: pylint --fail-under=10 src/

      - name: Generate Dependency Graph
        working-directory: Module_5
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pydeps src/app.py --noshow -T svg -o dependency.svg
          test -f dependency.svg

      - name: Run Pytest
       # run Pytest coverage verification here
        working-directory: Module_5
        run: pytest src/

      - name: Run Snyk Dependency Scan
        # run supply chain scanning pipeline here
        run: |
          npm install -g snyk
          snyk test || echo "Vulnerabilities found, but allowing pipeline to proceed."
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}